/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion2_lab7;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author KATHERINE
 */
public class Principal_Lab7 extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Lab7
     */
    public Principal_Lab7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pricipal_boton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        V_rec_LAN = new javax.swing.JTextField();
        nombre_LAN = new javax.swing.JTextField();
        v_trans_LAN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        boton_wam = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rou1 = new javax.swing.JTextField();
        rou2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pricipal_boton.setText("Crear Swicth");
        pricipal_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pricipal_botonMouseClicked(evt);
            }
        });
        jPanel1.add(pricipal_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 372, -1, -1));

        jLabel1.setText("V. Transferencia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 70, -1, -1));

        jLabel2.setText("V.Recepcion ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 132, -1, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 186, -1, -1));
        jPanel1.add(V_rec_LAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 129, 297, -1));
        jPanel1.add(nombre_LAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 183, 297, -1));
        jPanel1.add(v_trans_LAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 67, 297, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programacion2_lab7/cisco.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1240, 620));

        jTabbedPane1.addTab("LAN", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_wam.setText("Enalzar");
        boton_wam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_wamMouseClicked(evt);
            }
        });
        jPanel2.add(boton_wam, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 208, -1, -1));

        jLabel4.setText("IP router 1");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 70, -1, -1));

        jLabel5.setText("IP router 2");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 131, -1, -1));
        jPanel2.add(rou1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 67, 232, -1));
        jPanel2.add(rou2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 128, 232, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programacion2_lab7/cisco.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("WAN", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pricipal_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricipal_botonMouseClicked
        // TODO add your handling code here:
        try {
            //Ventana_LAN ventana_lan, String nombre, int v_transmicion, int v_recepcion, Router router
            Ventana_LAN ven_LAN=new Ventana_LAN();
            lan.add(new LAN(ven_LAN, nombre_LAN.getText(), Integer.parseInt(v_trans_LAN.getText()),
                    Integer.parseInt(V_rec_LAN.getText())));
            ven_LAN.s = lan.get(lan.size()-1);
            
            JOptionPane.showMessageDialog(this, "Swicth creado");
            System.out.println(lan);
            ven_LAN.setVisible(true);
        } catch (Exception e) {
        }
            
    }//GEN-LAST:event_pricipal_botonMouseClicked

    private void boton_wamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_wamMouseClicked
        // TODO add your handling code here:
        rou.getLista_router();
        
         boolean existe1=false;
            boolean existe2=false;
            
            for (int i = 0; i < rou.getLista_router().size(); i++) {
               if(rou.getLista_router().get(i).equals(rou1.getText())){
                   existe1=true;
               }
            }
            for (int i = 0; i < rou.getLista_router().size(); i++) {
               if(rou.getLista_router().get(i).equals(rou2.getText())){
                   existe2=true;
               }
            }
            
            
            if(existe1==true &&existe2==true){
                for (int i = 0; i < rou.getLista_router().size(); i++) {
               if(rou.getLista_router().get(i).equals(rou1.getText())){
                   R.setRou(rou.getLista_router().get(i));
                   System.out.println(R.getRou());
               }
                }
                for (int i = 0; i < rou.getLista_router().size(); i++) {
               if(rou.getLista_router().get(i).equals(rou2.getText())){
                   R.setRou(rou.getLista_router().get(i));
                   System.out.println(R.getRou());
               }
                }
                
            
            JOptionPane.showMessageDialog(this, "Routers enlazados");
            }else{
                 JOptionPane.showMessageDialog(this, "Routers no enlazados");
            }
            
    }//GEN-LAST:event_boton_wamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Lab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Lab7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField V_rec_LAN;
    private javax.swing.JButton boton_wam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nombre_LAN;
    public javax.swing.JButton pricipal_boton;
    private javax.swing.JTextField rou1;
    private javax.swing.JTextField rou2;
    private javax.swing.JTextField v_trans_LAN;
    // End of variables declaration//GEN-END:variables

//ArrayList<switch_1>  s_lan=new ArrayList();
ArrayList<LAN>  lan=new ArrayList();
//switch_1 s=new switch_1();
admi_router rou =new admi_router();
Router R=new Router();
        
}
